---
version: "3.9"

services:

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=CEST #optional
      - SUBDOMAINS=${SUBDOMAIN1}
      - TOKEN=d0012766-de71-491f-881e-be36452a9f52
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=true #optional
    volumes:
      - ./config/duckdns:/config #optional
    restart: unless-stopped

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CEST
      - SERVERURL=${SUBDOMAIN1} #optional
      - SERVERPORT=51820 #optional
      - PEERS=phone #optional
      - PEERDNS=1.1.1.1 #optional
      - INTERNAL_SUBNET=${WIREGUARD_SUBNET} #optional
      - ALLOWEDIPS=${WIREGUARD_SUBNET}/24,${LAN_SUBNET}/24 #optional
      - PERSISTENTKEEPALIVE_PEERS=all #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config/wireguard:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CEST
    volumes:
      - ./config/homeassistant:/config
    ports:
      - 8123:8123 #optional
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
